### ISSUE TITLE
REPORTE_PERSONALIZADO

### ISSUE THREAD

**Issue by Nayee123** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Nayee123#2]
[Reporte_TexBox_Personalizado_Nayeli_Anai_Gonzalez_Lopez.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Nayee123/files/6338057/Reporte_TexBox_Personalizado_Nayeli_Anai_Gonzalez_Lopez.pdf)

**Comment by Valentiin01** [comment]
Buen trabajo tienes 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
